#app/config/security.yml
security:
    encoders:
        HospitalBundle\Entity\Usuario:
             algorithm:         sha1
             encode_as_base64:  false
             iterations:        1

    role_hierarchy:
        ROLE_ADMIN:        ROLE_USER
        ROLE_SUPER_dmin:   [ ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]

    providers:
        administrators:
            entity: { class: HospitalBundle:Usuario }

    firewalls:
        secured_area:
            pattern:      ^/
            anonymous:   ~

    access_control:
        - { path: ^/admin, roles: ROLE_ADMIN }