HospitalBundle\Entity\Empleado:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idPersona:
            type: integer
        idCargo:
            type: integer
        idTipoEmpleado:
            type: integer
        idDependencia:
            type: integer
        idUsuario:
            type: integer
    lifecycleCallbacks: {  }
