HospitalBundle\Entity\Factura:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        idPersona:
            type: integer
        fechaGeneracion:
            type: datetime
    lifecycleCallbacks: {  }
