HospitalBundle\Entity\TipoExamen:
    type: entity
    table: null
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        nombre:
            type: string
            length: '45'
        descripcion:
            type: string
            length: '45'
    lifecycleCallbacks: {  }
